//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inso_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {

        [Display(Name = "کد رهگیری")]
        public int id { get; set; }

        [Display(Name = "نام")]
        public string firstName { get; set; }

        [Display(Name = "نام خانوادگی")]
        public string lastName { get; set; }

        [Display(Name = "کد ملی")]
        public string nationalId { get; set; }

        [Display(Name = "تاریخ تولد")]
        public string birthday { get; set; }

        [Display(Name = "موبایل")]
        public string mobile { get; set; }

        [Display(Name = "پست الکترونیک")]
        public string email { get; set; }

        [Display(Name = "نمایه کاربری")]
        public string avatar { get; set; }
    }
}
